export default {
  wrapper: `flex h-screen text-white w-full space-x-3`,
  videoFile: `w-full h-full`,
  videoDuration: `absolute bottom-0 right-0 bg-black text-white text-xs p-[5px]`,
  container: `flex flex-[0.7] justify-between flex-col`,
  profileContainer: `sticky top-0 flex flex-[0.3] flex-col border-2 border-gray-500 p-2 rounded-sm items-center`,
  buttonsContainer: `flex flex-col w-full`,
  sendContainer: `relative mt-4 bg-gray-700 h-[80px] rounded-lg py-4 px-2 flex items-center`,
  profileAvatar: `mr-1`,
  avatar: `rounded-none object-cover w-full h-fit max-h-[50%]`,
  inputContainer: `bg-gray-800 py-2 pl-3 pr-2 rounded-lg flex flex-1 items-center`,
  input: `input text-[16px] flex-1 text-white`,
  icon: `text-2xl cursor-pointer text-gray-400`,
  filesContainer: ` absolute overflow-x-auto w-full flex grid grid-cols-1 z-10 md:grid-cols-3 lg:grid-cols-4 animate-slide-fwd  top-[72px] px-1 py-2  rounded-b-lg left-0 bg-gray-800 bg-opacity-80`,
  imageFile: `w-full h-full object-cover`,
  fileContainer: `object-contain mx-1 my-1 h-24 mx-1 relative flex items-center justify-center`,
  // imageFileContainer: `object-contain mx-1 my-1 h-24 mx-1 relative flex items-center justify-center`,
  // videoFileContainer: `flex mx-1 my-1 items-center justify-center w-[90%] h-28 relative bg-black`,
  closeIcon: `absolute bg-black transition-all duration-200 bg-opacity-70 hover:bg-opacity-60 rounded-sm cursor-pointer -top-0 text-white -right-0`,
  button: `w-full h-10 disabled:text-gray-300 disabled:border-gray-300 rounded-full text-[18px] border-blue-400 hover:border-blue-500 hover:text-blue-300 transition-all duration-300 border-2 mt-4`,
  name: `font-semibold text-xl`,
  sendIcon: `ml-1 h-[26px] w-[26px] text-gray-400`,
  selectedImage: `w-[20px] h-[23px]`,
  infoContainer: `flex flex-col space-y-2`,
  info: `flex text-[20px] border-b border-gray-600 pb-1 items-center justify-between capitalize`,
  infoName: ``,
  infoValue: ``,
  postsContainer: ` overflow-y-scroll scrollbar-hide h-screen flex flex-col-reverse`,
  form: `flex mt-3 items-center border-2 border-gray-500 rounded-full h-12 pl-3 space-x-2`,
}
