export default {
  wrapper: `text-white`,
  imagesContainer: `border-b pb-3 border-gray-600 rounded-b-lg border-r border-l flex grid grid-cols-3 lg:grid-cols-5`,
  image: `cursor-pointer object-contain h-full block mx-auto w-[50%]`,
  senderContainer: `flex space-x-2 items-center`,
  senderInfoContainer: ``,
  firstImageContainer: `cursor-pointer border-gray-600 border-t rounded-t-lg border-r border-l w-full py-2 mt-2 px-auto mx-auto`,
  infoContainer: ``,
  name: `name`,
  postedAt: `text-sm text-gray-300`,
  text: `mt-3`,
  widgetsContainer: `flex items-center my-5`,
  widgetContainer: `flex transition-all duration-200 mr-1 cursor-pointer hover:bg-gray-500 rounded-md justify-center h-8 w-16 items-center`,
  avatar: `avatar w-[60px] h-[60px]`,
  icon: `text-xl mr-1`,
  widgetText: `text-gray-300`,
  commentForm: `flex items-center w-full h-10`,
  inputContainer: `flex items-center flex-1 px-3 rounded-md text-sm ml-2 bg-gray-800 h-full`,
  input: `flex-1 input`,
  sendIcon: `text-lg`,
  likedWidgetContainer: `flex transition-all duration-200 mr-1 bg-green-400 cursor-pointer h-8 w-16 rounded-md justify-center items-center`,
  likedContainer: `text-white`,
  likedIcon: `text-xl mr-1`,
  commentsContainer: `my-2 flex flex-col-reverse`,
  showAllCommentsText: `hover:underline text-gray-400 font-semibold mb-3 cursor-pointer`,
}
