export default {
  wrapper: `flex items-center h-screen w-screen`,
  backgroundImage: `w-screen z-0 h-screen fixed top-0 inset-0 object-cover`,
  container: `bg-black bg-opacity-50 px-10 flex flex-col justify-center items-start h-full shadow-r-5xl w-[70%] max-w-4xl fixed z-10`,
  title: `text-white text-2xl flex items-end font-semibold`,
  dot: `text-6xl text-blue-600`,
  alreadyAMemberText: `text-[18px] my-4 text-gray-400 capitalize`,
  loginText: `text-blue-500 cursor-pointer hover:underline`,
  form: `w-full flex flex-col`,
  nameInputContainer: `w-full flex flex-col md:flex-row justify-between items-center`,
  inputContainer: `relative flex w-full  items-center my-1 bg-black text-gray-400 bg-opacity-50 rounded-lg p-2`,
  label: `absolute top-1 text-xs`,
  input: `input flex-1 mt-4 text-white`,
  icon: ` text-xl`,
  button: `bg-blue-600 disabled:cursor-not-allowed text-white  py-2 rounded-full mt-4 w-full xl:w-[70%] mx-auto`,
}
