export default {
  wrapper: `modal`,
  container: `max-w-lg w-full flex flex-col`,
  header: `bg-gray-600 w-full h-10 flex justify-between items-center px-3`,
  backContainer: `flex cursor-pointer items-center`,
  backIcon: `text-lg`,
  backText: `mb-[1px] hover:underline font-semibold`,
  title: `font-semibold text-[21px]`,
  closeIcon: `text-lg cursor-pointer`,
  nobodyToAdd: `text-gray-300 text-[21px] font-semibold h-16 flex items-center justify-center`,
  searchContainer: `flex h-12 border-b border-t items-center w-full px-3`,
  input: `input flex-1`,
  searchIcon: `text-lg`,
  friendsContainer: `w-full`,
  friendContainer: `flex `,
  potentialMembersContainer: `flex items-center grid grid-cols-3 mt-3`,
  potentialMemberContainer: `flex bg-blue-500 px-2 h-[30px] bg-opacity-70 rounded-sm items-center w-fit`,
  potentialMemberName: `flex-1 text-sm`,
  removePotentialMemberIcon: `mt-1 cursor-pointer ml-1`,
  addMembers: `bg-blue-900 disabled:bg-gray-600 w-full text-center h-8 rounded-full`,
}
