export default {
  wrapper: `w-full flex flex-col mt-2`,
  container: ` w-[70%]`,
  messageContainer: `relative px-3 rounded-xl rounded-br-sm mb-2 h-fit py-3 mx-2`,
  text: ``,
  replyIcon: `absolute bottom-1 right-1 cursor-pointer`,
  senderContainer: `flex items-center mr-3 space-x-2 justify-end `,
  sentAt: `text-[14px] text-gray-300 mb-1`,
  senderName: `font-semibold text-[16px]`,
  avatar: `w-[35px] h-[35px]`,
  answerContainer: `mt-2 mb-4  bg-opacity-50 border-l-2 border-gray-500 hover:border-gray-400 left-16 right-16 pl-2 py-1 bg-gray-700 `,
  answerName: `font-semibold text-sm`,
  answerText: `text-sm`,
  answerMessageImagesLength: ``,
  answerSenderContainer: `relative pt-5 flex items-center`,
  repliedTo: `absolute top-1 text-sm text-gray-300`,
  answerSenderAvatar: `w-8 h-8 ml-2`,
  answerSenderText: ``,
  imagesContainer: `flex justify-center grid grid-cols-2`,
  image: `cursor-pointer max-h-60`,
}
